rvm: 3.0.2
language: ruby
addons:
  postgresql: "9.4"
before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - curl -Os https://uploader.codecov.io/latest/macos/codecov
  - chmod +x codecov
  # Used if we have javascript on the front end
  # - bundle exec rails webpacker:compile
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
script: bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - ./codecov -t ${CODECOV_TOKEN}
