language: ruby
addons:
  postgresql: "9.4"
before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test
install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
script: bundle exec rake
rvm: 3.0.2
